const CATEGORIES = [
  {
    id: "0",
    label: "add_custom_category",
    icon: "add-circle",
    color: "#FF6B35",
  },
  { id: "1", label: "t-shirt", icon: "shirt", color: "#F97316" },
  { id: "2", label: "dress", icon: "woman", color: "#A855F7" },
  { id: "3", label: "pants", icon: "man", color: "#22C55E" },
  { id: "4", label: "jacket", icon: "shirt-outline", color: "#F43F5E" },
  { id: "5", label: "shoes", icon: "footsteps", color: "#FDBA74" },
  { id: "6", label: "accessory", icon: "watch", color: "#64748B" },
  { id: "7", label: "shirt", icon: "shirt-outline", color: "#0EA5E9" },
  { id: "8", label: "skirt", icon: "woman-outline", color: "#EC4899" },
  { id: "9", label: "shorts", icon: "walk", color: "#06B6D4" },
  { id: "10", label: "sweater", icon: "snow", color: "#8B5CF6" },
  { id: "11", label: "coat", icon: "shield", color: "#6B7280" },
  { id: "12", label: "boots", icon: "footsteps-outline", color: "#78350F" },
  { id: "13", label: "bag", icon: "bag", color: "#BE185D" },
  {
    id: "14",
    label: "jewelry",
    icon: "diamond-outline",
    color: "#FBBF24",
  },
  { id: "15", label: "hat", icon: "triangle", color: "#7C3AED" },
  { id: "16", label: "jeans", icon: "person", color: "#1D4ED8" },
  { id: "17", label: "blouse", icon: "shirt-sharp", color: "#DB2777" },
  { id: "18", label: "suit", icon: "business", color: "#374151" },
  { id: "19", label: "vest", icon: "man-outline", color: "#DC2626" },
  { id: "20", label: "cardigan", icon: "snow-outline", color: "#9333EA" },
  {
    id: "21",
    label: "blazer",
    icon: "business-outline",
    color: "#0F766E",
  },
  { id: "22", label: "tunic", icon: "woman-sharp", color: "#EA580C" },
  { id: "23", label: "crop_top", icon: "shirt-sharp", color: "#E11D48" },
  { id: "24", label: "tank_top", icon: "man-sharp", color: "#0891B2" },
  { id: "25", label: "leggings", icon: "walk-outline", color: "#7C3AED" },
  { id: "26", label: "jogger", icon: "fitness", color: "#059669" },
  { id: "27", label: "jumpsuit", icon: "body", color: "#B91C1C" },
  { id: "28", label: "bikini", icon: "sunny", color: "#F59E0B" },
  { id: "29", label: "scarf", icon: "ribbon", color: "#DB2777" },
  { id: "30", label: "belt", icon: "ellipse", color: "#78350F" },
  { id: "31", label: "glasses", icon: "glasses", color: "#374151" },
  { id: "32", label: "gloves", icon: "hand-left", color: "#1F2937" },
  { id: "33", label: "socks", icon: "chevron-up", color: "#6B7280" },
  { id: "34", label: "sandals", icon: "flower", color: "#FDBA74" },
  {
    id: "35",
    label: "sneakers",
    icon: "baseball",
    color: "#10B981",
  },
  {
    id: "36",
    label: "heels",
    icon: "triangle-outline",
    color: "#EC4899",
  },
  { id: "37", label: "tie", icon: "remove", color: "#1E40AF" },
  { id: "38", label: "hoodie", icon: "shirt", color: "#6366F1" },
  { id: "39", label: "polo_shirt", icon: "golf", color: "#059669" },
  { id: "40", label: "kimono", icon: "flower-outline", color: "#F472B6" },
  { id: "41", label: "mittens", icon: "hand-left-outline", color: "#A1A1AA" },
  { id: "42", label: "watch", icon: "watch-outline", color: "#FACC15" },
  {
    id: "43",
    label: "bracelet",
    icon: "hardware-chip-outline",
    color: "#F87171",
  },
  { id: "44", label: "necklace", icon: "medal-outline", color: "#FB923C" },
  { id: "45", label: "ring", icon: "ellipse-outline", color: "#34D399" },
  { id: "46", label: "anklet", icon: "link-outline", color: "#A78BFA" },
  { id: "47", label: "pajamas", icon: "bed-outline", color: "#F472B6" },
  {
    id: "48",
    label: "bathrobe",
    icon: "accessibility-outline",
    color: "#60A5FA",
  },
  { id: "49", label: "swimsuit", icon: "water-outline", color: "#2DD4BF" },
  {
    id: "50",
    label: "beach_dress",
    icon: "umbrella-outline",
    color: "#F4ABF4",
  },
  { id: "51", label: "pareo", icon: "bookmarks-outline", color: "#FCD34D" },
  { id: "52", label: "sports_bra", icon: "barbell-outline", color: "#FCA5A5" },
  {
    id: "53",
    label: "sports_shorts",
    icon: "bicycle-outline",
    color: "#93C5FD",
  },
  { id: "54", label: "sweatpants", icon: "walk", color: "#A3A3A3" },
  { id: "55", label: "tracksuit_top", icon: "body-outline", color: "#D4D4D4" },
  { id: "56", label: "raincoat", icon: "rainy-outline", color: "#86EFAC" },
  { id: "57", label: "windbreaker", icon: "flag-outline", color: "#FDE047" },
  { id: "58", label: "ski_jacket", icon: "snow-outline", color: "#A5F3FC" },
  { id: "59", label: "ski_pants", icon: "snow", color: "#E0E7FF" },
  {
    id: "60",
    label: "thermal_underwear",
    icon: "thermometer-outline",
    color: "#FECACA",
  },
];

module.exports = { CATEGORIES };
