export const STYLES = [
  {
    id: "custom",
    label: "add_custom_style",
    icon: "add-circle",
    color: "#FF6B35",
  },
  { id: "casual", label: "casual", icon: "home", color: "#6366F1" },
  { id: "formal", label: "formal", icon: "briefcase", color: "#059669" },
  { id: "sporty", label: "sporty", icon: "fitness", color: "#DC2626" },
  { id: "elegant", label: "elegant", icon: "diamond", color: "#7C2D12" },
  { id: "trendy", label: "trendy", icon: "flash", color: "#BE185D" },
  { id: "vintage", label: "vintage", icon: "time", color: "#92400E" },
  { id: "bohemian", label: "bohemian", icon: "leaf", color: "#059669" },
  { id: "minimalist", label: "minimalist", icon: "remove", color: "#374151" },
  { id: "street", label: "street", icon: "car", color: "#F59E0B" },
  { id: "classic", label: "classic", icon: "library", color: "#1F2937" },
  { id: "retro", label: "retro", icon: "radio", color: "#EC4899" },
  { id: "gothic", label: "gothic", icon: "moon", color: "#4B5563" },
  { id: "preppy", label: "preppy", icon: "school", color: "#10B981" },
  { id: "romantic", label: "romantic", icon: "heart", color: "#F472B6" },
  { id: "edgy", label: "edgy", icon: "flash-outline", color: "#EF4444" },
  { id: "chic", label: "chic_modern", icon: "star", color: "#8B5CF6" },
  { id: "artsy", label: "artsy", icon: "brush", color: "#06B6D4" },
  { id: "grunge", label: "grunge", icon: "skull", color: "#6B7280" },
  { id: "hipster", label: "hipster", icon: "glasses", color: "#F59E0B" },
  { id: "punk", label: "punk", icon: "flame", color: "#DC2626" },
  { id: "glam", label: "glamorous", icon: "sparkles", color: "#FBBF24" },
  { id: "kawaii", label: "kawaii", icon: "happy", color: "#FB7185" },
  { id: "cyber", label: "cyber", icon: "hardware-chip", color: "#3B82F6" },
  { id: "cottagecore", label: "cottagecore", icon: "flower", color: "#84CC16" },
  {
    id: "dark_academia",
    label: "dark_academia",
    icon: "book",
    color: "#78350F",
  },
  { id: "y2k", label: "y2k", icon: "planet", color: "#A855F7" },
  {
    id: "soft_girl",
    label: "soft_girl",
    icon: "heart-outline",
    color: "#FBBF24",
  },
  {
    id: "e_girl",
    label: "e-girl",
    icon: "game-controller",
    color: "#EC4899",
  },
  {
    id: "academia",
    label: "academic",
    icon: "library-outline",
    color: "#92400E",
  },
  {
    id: "sporty_chic",
    label: "sporty_chic",
    icon: "basketball",
    color: "#059669",
  },
  {
    id: "boho_chic",
    label: "boho_chic",
    icon: "flower-outline",
    color: "#D97706",
  },
  { id: "urban", label: "urban", icon: "business", color: "#374151" },
  {
    id: "festival",
    label: "festival",
    icon: "musical-notes",
    color: "#7C3AED",
  },
  { id: "athleisure", label: "athleisure", icon: "bicycle", color: "#10B981" },
  { id: "lounge", label: "lounge", icon: "bed", color: "#A78BFA" },
  { id: "western", label: "western", icon: "key", color: "#92400E" },
  { id: "safari", label: "safari", icon: "compass", color: "#D97706" },
  { id: "nautical", label: "nautical", icon: "boat", color: "#3B82F6" },
  {
    id: "military",
    label: "military",
    icon: "shield-checkmark",
    color: "#0F766E",
  },
  { id: "futuristic", label: "futuristic", icon: "rocket", color: "#4B5563" },
  { id: "rave", label: "rave", icon: "musical-note", color: "#EC4899" },
  { id: "skater", label: "skater", icon: "ice-cream", color: "#F59E0B" },
  { id: "biker", label: "biker", icon: "bicycle-outline", color: "#1F2937" },
  {
    id: "cowboy_cowgirl",
    label: "cowboy/cowgirl",
    icon: "key-outline",
    color: "#78350F",
  },
  { id: "surfer", label: "surfer", icon: "water", color: "#06B6D4" },
  { id: "tropical", label: "tropical", icon: "leaf-outline", color: "#84CC16" },
  {
    id: "avant_garde",
    label: "avant-garde",
    icon: "color-palette",
    color: "#BE185D",
  },
  {
    id: "country_club",
    label: "country_club",
    icon: "golf-outline",
    color: "#059669",
  },
  {
    id: "hip_hop",
    label: "hip_hop",
    icon: "musical-notes-outline",
    color: "#FBBF24",
  },
  {
    id: "rocker",
    label: "rocker",
    icon: "musical-note-outline",
    color: "#DC2626",
  },
  { id: "tomboy", label: "tomboy", icon: "male", color: "#374151" },
  {
    id: "balletcore",
    label: "balletcore",
    icon: "accessibility",
    color: "#F472B6",
  },
  {
    id: "fairycore",
    label: "fairycore",
    icon: "sparkles-outline",
    color: "#A855F7",
  },
];
